version: 2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk:470.0.0

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: echo "Building..."

  test:
    docker:
      - image: google/cloud-sdk:470.0.0

    steps:
      - checkout
      - run:
          name: Test
          command: echo "Testing..."

  deploy:
    docker:
      - image: google/cloud-sdk:470.0.0

    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Deploying..."

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
